services:
  - type: web
    name: calorie-app-backend
    runtime: node
    plan: free
    rootDir: backend
    buildCommand: npm install && npm run seed
    startCommand: npm start
    envVars:
      - key: JWT_SECRET
        generateValue: true
      - key: PORT
        value: 3000
